#Configure Logging
quarkus:
  log:
    level: INFO
    min-level: TRACE
    category:
      "org.gameontext.player":
        level: TRACE
      "org.gameontext.player.control":
        level: TRACE
      "org.gameontext.player.entity":
        level: TRACE
      "org.gameontext.player.utils":
        level: TRACE
      "org.gameontext.signed":
        level: TRACE        

#Configure root path for quarkus (note, not honored by websocket registrations)
  http:
    root-path: /players
#Configure port to be compatible with previous player service =)
    port: 9080
#Ensure we're listening to all interfaces 
    host: 0.0.0.0    

#Force health to paths compatible with GameOn
    non-application-root-path: ${quarkus.http.root-path}

  smallrye-health:
    root-path: health
    liveness-path: liveness